use CDC to publish alerts to a kafka topic
tidepool-org/development pull request #271
Opened 2024-02-22 20:00 UTC by ewollesen

These alerts will be used to trigger push notifications in support of the care partner alerting app.

BACK-2504

2024-03-14 13:07 UTC, toddkazakov requested changes

2024-03-14 13:07 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/8-data-set-sources-kafka-connector.yaml
> +    collection: deviceDataSets
Is it required to re-evaluate alerts when a new dataset is created?

2024-03-14 13:07 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    pipeline: '[ { $match: { "fullDocument.provenance.clientID": { $regex: "^org\.tidepool(\.[^.]+)?\.Loop$" } } } ]'
Should the regex be case insensitive?

2024-03-14 13:07 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    copy.existing: true
You don't want to copy existing data to kafka, so this should be false

2024-03-14 13:07 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    topic.suffix: "-alerts"
Should the suffix be `loop` instead of alerts?

2024-03-14 13:48 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-data-set-sources-kafka-connector.yaml
> +    collection: deviceDataSets
Not that I'm aware of. When you asked me to add provenance to data sets, I guess I assumed that you foresaw some desire to have them included in the CDC, was that not the case?

2024-03-14 13:50 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    pipeline: '[ { $match: { "fullDocument.provenance.clientID": { $regex: "^org\.tidepool(\.[^.]+)?\.Loop$" } } } ]'
It will work either way. I'm guessing you're prefer that it were, so I'll add the flags.

2024-03-14 13:51 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    topic.suffix: "-alerts"
They communicate slightly different things. Right now either works. If we later restrict this query more, alerts might make more sense.

2024-03-14 13:53 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/8-data-set-sources-kafka-connector.yaml
> +    collection: deviceDataSets
No need to have them in CDC if we are not going to process those events.

2024-03-14 15:54 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-data-set-sources-kafka-connector.yaml
> +    collection: deviceDataSets
Out of curiousity, why do you want provenance in the data sets then?

2024-03-14 15:54 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    pipeline: '[ { $match: { "fullDocument.provenance.clientID": { $regex: "^org\.tidepool(\.[^.]+)?\.Loop$" } } } ]'
After some discussion, we went with a string match.. Plus I was looking at the wrong values, I need to match Keycloak client ids, not the clients from the data set records.

2024-03-14 15:55 UTC, ewollesen commented on charts/tidepool/charts/data/templates/8-device-data-kafka-connector.yaml
> +    topic.suffix: "-alerts"
We decided to leave it as is

2024-03-20 21:39 UTC, toddkazakov approved these changes

2024-03-20 21:48 UTC, merged