care partner alerts APNs configuration
tidepool-org/development pull request #296
Opened 2024-10-07 16:53 UTC by ewollesen

2024-10-08 11:08 UTC, toddkazakov requested changes

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/values.yaml
> +    pusherAPNSKeyID: "QA3495JW4S"
```suggestion
    PusherAPNSKeyID: "QA3495JW4S"
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/values.yaml
> +    pusherAPNSTeamID: "75U4X84TEG"
```suggestion
    PusherAPNSTeamID: "75U4X84TEG"
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/values.yaml
> +    pusherAPNSBundleID: "org.tidepool.carepartner"
```suggestion
    PusherAPNSBundleID: "org.tidepool.carepartner"
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/1-deployment.yaml
> +              key: pusherAPNSBundleID
```suggestion
              key: PusherAPNSBundleID
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/1-deployment.yaml
> +              key: pusherAPNSTeamID
```suggestion
              key: PusherAPNSTeamID
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/1-deployment.yaml
> +              key: pusherAPNSKeyID
```suggestion
              key: PusherAPNSKeyID
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/1-deployment.yaml
> +              key: pusherAPNSSigningKey
```suggestion
              key: PusherAPNSSigningKey
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/0-secret.yaml
> +  pusherAPNSSigningKey: {{ .Values.secret.data_.pusherAPNSSigningKey | default "" | quote }}
```suggestion
  PusherAPNSSigningKey: {{ .Values.secret.data_.Pusher.APNS.SigningKey | default "" | quote }}
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/0-configmap.yaml
> +  pusherAPNSKeyID: {{ .pusherAPNSKeyID | default "" }}
```suggestion
  pusherAPNSKeyID: {{ .PusherAPNSKeyID | default "" }}
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/0-configmap.yaml
> +  pusherAPNSTeamID: {{ .pusherAPNSTeamID | default "" }}
```suggestion
  PusherAPNSTeamID: {{ .pusherAPNSTeamID | default "" }}
```

2024-10-08 11:08 UTC, toddkazakov commented on charts/tidepool/charts/data/templates/0-configmap.yaml
> +  pusherAPNSBundleID: {{ .pusherAPNSBundleID | default "" }}
```suggestion
  PusherAPNSBundleID: {{ .pusherAPNSBundleID | default "" }}
```

2024-11-22 17:47 UTC, toddkazakov approved these changes
Please create the required configmaps and secrets in all environments before merging to master

2024-11-23 12:02 UTC, toddkazakov approved these changes

2025-01-28 20:17 UTC, ewollesen commented
> Please create the required configmaps and secrets in all environments before merging to master

QA changes here: https://github.com/tidepool-org/cluster-qa2/pull/1545/files

2025-02-04 10:07 UTC, toddkazakov approved these changes

2025-02-10 17:19 UTC, toddkazakov approved these changes

2025-02-10 21:19 UTC, merged