platform upload user list for jellyfish migration
tidepool-org/development pull request #297
Opened 2024-10-09 00:33 UTC by jh-bate

See https://github.com/tidepool-org/jellyfish/pull/203

2024-10-09 03:45 UTC, darinkrauss requested changes
Consider the rename, but definitely revert the `docker-compose.yaml` change (as we don't want to give any indication it is being used).

2024-10-09 03:45 UTC, darinkrauss commented on docker-compose.yml
> +      PLATFORM_UPLOAD_USERS: ''
You can drop this. We don't support this and it needs to be deleted. The whole repo needs to be cleaned up.

2024-10-09 03:45 UTC, darinkrauss commented on charts/tidepool/charts/jellyfish/templates/0-configmap.yaml
> +  PlatformUploadUsers: {{ .Values.configmap.data.PlatformUploadUsers }}
I might call this `UploaderPlatformUserIds` and `UPLOADER_PLATFORM_USER_IDS` so it is clear.

2024-12-06 02:18 UTC, jh-bate commented
closing as now doing this in the jellyfish service itself

2024-12-06 02:18 UTC, closed without merging