[BACK-3269] basic settings for oauth
tidepool-org/development pull request #303
Opened 2024-11-28 02:30 UTC by jh-bate

2024-12-02 23:04 UTC, darinkrauss reviewed
A couple of questions, but it looks fine pending one question in Slack: https://tidepoolteam.slack.com/archives/C07F46SL6QZ/p1733180554738719

Once that question is answered, I'll approve.

2024-12-02 23:04 UTC, darinkrauss commented on charts/tidepool/charts/abbott/templates/0-configmap.yaml
> +  Scopes: "openid,offline,read.glucose,read.device"
Are these scopes right for Abbott?

2024-12-02 23:04 UTC, darinkrauss commented on charts/tidepool/charts/abbott/values.yaml
> +  clientURL: "https://api.libreview.io"
Is this the default URL for production?

2024-12-03 04:05 UTC, jh-bate commented on charts/tidepool/charts/abbott/values.yaml
> +  clientURL: "https://api.libreview.io"
yes - from the docs

2024-12-03 04:05 UTC, jh-bate commented on charts/tidepool/charts/abbott/templates/0-configmap.yaml
> +  Scopes: "openid,offline,read.glucose,read.device"
yes- its what we are using in the sandbox

2024-12-04 03:20 UTC, darinkrauss requested changes
Let's remove the specific URLs here as they aren't required and can be specified elsewhere.

2024-12-04 03:20 UTC, darinkrauss commented on charts/tidepool/charts/abbott/templates/0-configmap.yaml
> +  ClientURL: {{ .Values.configmap.clientURL | default "https://api.libreview.io" }}
Why don't we just remove the defaults here.
```suggestion
  TokenURL: {{ .Values.configmap.tokenURL }}
  AuthorizeURL: {{ .Values.configmap.authorizeURL }}
  ClientURL: {{ .Values.configmap.clientURL }}
```
We'll just need to ensure they are specified in the cluster config files.

2024-12-04 03:20 UTC, darinkrauss commented on charts/tidepool/charts/abbott/values.yaml
> +  clientURL: "https://api.libreview.io"
Let's just use `""` here for `clientURL`.
```suggestion
  clientURL: ""
```

2024-12-04 03:20 UTC, darinkrauss commented on Tiltconfig.yaml
> +    clientURL: "https://api.partner.int.adc-lv.io"
Why don't we just remove these three URLs from this file and just use ""? We'll just include them with the client id and secret in the 1Password entries for developers to add to their `local/Tiltconfig.yaml`.
```suggestion
    tokenURL: ""
    authorizeURL: ""
    clientURL: ""
```

2024-12-07 17:26 UTC, darinkrauss requested changes
LGTM, we just need to squash down to one commit and force-push it before merging.

2024-12-10 18:17 UTC, darinkrauss approved these changes
A couple of minor suggestions per our discussion yesterday, but otherwise LGTM!

2024-12-10 18:17 UTC, darinkrauss commented on charts/tidepool/charts/abbott/values.yaml
> +  redirectURL: ""
Do we want to add defaults for `tokenURL` and `authorizeURL` here, too, per our discussion yesterday? Perhaps alphabetically ordered?

2024-12-10 18:17 UTC, darinkrauss commented on charts/tidepool/charts/abbott/README.md
> +| configmap.redirectURL | string | `""` |  |
Perhaps add the other configmap fields here, too?

2024-12-17 21:58 UTC, darinkrauss requested changes
Changes needed before merge.

2025-07-29 21:29 UTC, closed without merging